name: week5_firebase_auth_app
description: "Week 5 Task - Firebase Authentication and Firestore Database (Flutter Internship Cycle 2)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # UI / UX
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
